### ISSUE TITLE
Problem with connection with database.

### ISSUE THREAD

**Issue by maciekkukuczka** [scrappyCoco/SQL-Server-Administration-Tool#1]
HI!

I created connection in Data Grip, but "Choose datasource" window in SQLSAT is empty.

![image](https://user-images.githubusercontent.com/32330973/74447109-20694280-4e79-11ea-83a4-7f6ac15b7555.png)

**Comment by scrappyCoco** [comment]
Hi!
Are you sure that the the connection have been created to MS SQL in the Database explorer?
Try to see [doc](https://github.com/scrappyCoco/SQL-Server-Administration-Tool/wiki/Connection)

**Comment by maciekkukuczka** [comment]
I think so.



--------
Sorry,
I defined database in DataGrip external app instead in Rider. My bad...

**Comment by scrappyCoco** [comment]
Thanks for reply! Feel free to ask any questions.
